version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: "1.24"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
          timeout: 10m

workflows:
  main:
    jobs:
      - build_and_test
