version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build_and_test:
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.18' # Specify a version tag
    steps:
      - checkout # Checkout source code
      - go/load-cache # Load cached Go modules
      - go/mod-download # Run 'go mod download'
      - go/save-cache # Save Go modules to cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
          timeout: 10m

workflows:
  main:
    jobs:
      - build_and_test